### ISSUE TITLE
Testing framework for aurelia cards

### ISSUE THREAD

**Issue by MaanasaPriyaa** [urbanriskmap/petabencana.id#14]
Figure out how testing would work in this framework and present it to the team

**Comment by MaanasaPriyaa** [comment]
@talltom Jasmine or Mocha? Which one do you think is the better choice? I am open to other suggestions as well.

**Comment by matthewberryman** [comment]
Looks like there's some stuff from jasmine already there as part of aurealia (not sure if/how it's used, but @mgvarley can comment), and jasmine looks to be more complete—see http://thejsguy.com/2015/01/12/jasmine-vs-mocha-chai-and-sinon.html particularly in-built support for assertions—so I would say go with that.

**Comment by mgvarley** [comment]
Hi guys - just checked the CLI and yes, Jasmine plumbing is built in as part of the setup.  Never used Jasmine personally but have tried both Mocha and Chai and fairly similar once you get used ot the slightly different syntax.  Imagine Jasmine is not that different so might be worth trying if its already there.








>

**Comment by MaanasaPriyaa** [comment]
Alright. I wanted to check if we will be missing out on any functionality/ease of use if we are going to use Jasmine. IIRC, mocha & chai were used in our old petajakarta repo.

**Comment by abrahamq** [comment]
I've been working on this and have some progress- I've got karma tests running on browser stack, but I can't seem to get aurelia to play nice. I want to do something like this: http://patrickwalters.net/unit-testing-your-es6-view-models-my-best-practices-for-aurelia/ where you can make aurelia fill out the depenendecy injections for a view model, but doing 

`import {Container} from 'aurelia-dependency-injection';`

Only gives me an undefined Container object.... Not sure where to go with this. 

There's 3 different places where this could be going wrong: in aurelia.json, in karma.conf.js, and in aurelia-karma.js. No idea where to go from here. Latest code showing this problem is on df166d6

**Comment by MaanasaPriyaa** [comment]
I am not sure if unit tests need to use DI. We should mock the things to be injected in each view-model. More on this - http://stackoverflow.com/questions/36944463/how-do-you-unit-test-that-methods-such-as-ok-were-called-in-aurelia-dialog-usi 

Thoughts?

**Comment by abrahamq** [comment]
Just spent 3 hours on this issue and got pretty much nowhere. I think that some of the problems lie in the aurelia-karma.js file that's doing string manipulations in the url to try to load stuff through requirejs. Ugh. Going to mock stuff out for now, although we should really be able to do some really nice things like: https://github.com/aurelia/testing/blob/master/doc/article/en-US/testing-components.md . When I try to do StageComponent.withResource(' path to file'), I get 404's from the karma server.

**Comment by talltom** [comment]
We've got a test framework! https://travis-ci.org/urbanriskmap/petabencana.id
Thanks @abrahamq and @MaanasaPriyaa 

Closing this, please open new issues for specific tests as need.
