### ISSUE TITLE
Landing Page Map

### ISSUE THREAD

**Issue by anexact** [urbanriskmap/petabencana.id#210]
FY17Ext Dev Meeting Field Office 01 _ request for integration of a PB Landing Map with dots to replace the text box _ NM has versions that can be used as required

**Comment by talltom** [comment]
As described in #211 we can't navigate using the map.

We will still need the popup box so that users who are outside of Indonesia / no geolocation can select a city, but we could add points to highlight which cities are currently operational?

What are your thoughts on this? See attached picture.

![screen shot 2017-08-21 at 10 38 50 am](https://user-images.githubusercontent.com/944642/29524192-28942a1a-865d-11e7-9fc6-5f0353f7d2da.png)

**Comment by anexact** [comment]
Yes, looks good. The question from FO was whether we could use an "image" of a map with cities on it, but then when you click the highlight area for that city, it would appear to Zoom into the map, but really was in effect just loading that city's data? As with Unique ID event pins, could they appear at top level, but also, in the case of zooming back out, if you could see, say, Bandung, then you would click it to drill down another level. Just UX stylin' questions from FO squad, but good to discuss options for future deployments in Java and beyond.

**Comment by talltom** [comment]
Yes, using an image is technically possible, and we investigated this at the start of PB build, however starts to cause problems on mobiles with small screens.

For future reference - I think maps for each city, and push people to their city, for example yogyakarta.petabencana.id

**Comment by anexact** [comment]
Yes, I like this as a solution: from Landing page, you drill into a new domain, etc.
