### ISSUE TITLE
documentation out of date + things trashed in merge?

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/petabencana.id#35]
The main README.md file (the one in the aurelia subdirectory is gone, but I guess we want to keep some of it) refers to the use of gulp*, but there's no gulp file. I guess we want to keep using aurelia build, however along with #33 there have been the removal of some aurelia packages, the addition of some gulp packages, etc. I get the feeling some things may have been lost in all the merges?

*Note that if we need any new globally installed npm packages for build then it's best if I be informed beforehand (rather than seeing things break in jenkins).

**Comment by mgvarley** [comment]
Simplest approach might be to take the current src folder and then merge this in to the previous template then install any required vendor libraries? Happy to help 

m

Sent with Unibox

**Comment by talltom** [comment]
Okay, tagging @abrahamq @MaanasaPriyaa @ojha-url as this trashed merged has broken things for everyone and is going to hold us up. Is a fix in progress?

**Comment by matthewberryman** [comment]
Sounds great @mgvarley  (although we need to revisit the README.md also and probably copy and paste stuff in from the old aurelia README into the main README.md). Let's add to agenda for our hangout soon.

**Comment by ojha-url** [comment]
Hi all, sorry for the disruption; me @MaanasaPriyaa and @abrahamq will be meeting soon to restore any missing scripts, packages resulting from the merge. README.md will be updated to document the latest code.

**Comment by matthewberryman** [comment]
I'd say let @mgvarley have a poke first particularly as he knows aurelia and the way it works with npm.

**Comment by talltom** [comment]
Thanks @ojha-url -> @matthewberryman are you happy with those updates? If so can you close this issue.

Next step is to move stuff into the root of the directory but that can wait, and should be a separate issue.

**Comment by matthewberryman** [comment]
No, I'm not happy for the following reasons:
* There are two README.md files with conflicting information as to what to do.
* Neither of the README.md files refers to the build scripts back in package.json
* The one in the top level folder refers to installing gulp-cli globally, however there's no reference to the use of gulp in either README.md file, nor in the package.json scripts. 
* There's a reference to gulp-cli in package.json that shouldn't be there (as it shouldn't go in node_modules but needs to be installed globally if required).
Assigning to @talltom for now in order to manage this and help figure out who should do what.

**Comment by matthewberryman** [comment]
Also, if gulp is required, then I'm not sure why you'd install both gulp-cli and gulp globally? If it's anything like grunt then you would install the -cli one globally and then gulp-* requirements in node_modules (through use of package.json).

**Comment by ojha-url** [comment]
@MaanasaPriyaa can you fix both README.md files, as gulp-cli is no more needed, right?

**Comment by matthewberryman** [comment]
We really need to have just one README.md file for this (bearing in mind #34 but also for clarity).

**Comment by mgvarley** [comment]
I strongly recommend not removing any dev dependencies from package.json as this is what aurelia-cli generates when you create the skeleton application using au new.  Below are a list of the default dependencies created for a new project and all of these should be left intact, you are of course free to add new dependencies.  There is no harm in having something referenced as a dev dependency and also installed globally, it just means that a developer can download the project, run npm install and be up and running right away rather than have to scan through the docs and look for a list of global installs.  It also protects the project from globals which are on different versions.  The aurelia cli itself can be installed with npm install aurelia-cli -g


  "dependencies": {
    "aurelia-bootstrapper": "^1.0.0",
    "aurelia-fetch-client": "^1.0.0",
    "aurelia-animator-css": "^1.0.0",
    "bluebird": "^3.4.1"
  },
  "peerDependencies": {},
  "devDependencies": {
    "aurelia-cli": "^0.21.0",
    "aurelia-testing": "^1.0.0-beta.2.0.0",
    "aurelia-tools": "^0.2.2",
    "browser-sync": "^2.13.0",
    "connect-history-api-fallback": "^1.2.0",
    "gulp": "github:gulpjs/gulp#4.0",
    "gulp-changed-in-place": "^2.0.3",
    "gulp-plumber": "^1.1.0",
    "gulp-rename": "^1.2.2",
    "gulp-sourcemaps": "^2.0.0-alpha",
    "gulp-notify": "^2.2.0",
    "minimatch": "^3.0.2",
    "through2": "^2.0.1",
    "uglify-js": "^2.6.3",
    "vinyl-fs": "^2.4.3",
    "babel-eslint": "^6.0.4",
    "babel-plugin-syntax-flow": "^6.8.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-es2015-modules-amd": "^6.8.0",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.10.3",
    "babel-plugin-transform-flow-strip-types": "^6.8.0",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-es2015-loose": "^7.0.0",
    "babel-preset-stage-1": "^6.5.0",
    "babel-polyfill": "^6.9.1",
    "babel-register": "^6.9.0",
    "gulp-babel": "^6.1.2",
    "gulp-eslint": "^2.0.0",
    "jasmine-core": "^2.4.1",
    "karma": "^0.13.22",
    "karma-chrome-launcher": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-babel-preprocessor": "^6.0.1"
  }





>

**Comment by matthewberryman** [comment]
"just means that a developer can download the project, run npm install and be up and running right away rather than have to scan through the docs and look for a list of global installs"
I'm not sure how having it in packages.json helps with this unless you also modify the scripts to refer to those CLI tools as installed under node_modules (something to add to the to-do list, then).

**Comment by mgvarley** [comment]
Hi Matthew - I just mean that the developer can download, and run npm install, it will install everything locally so no need for specific global modules which may or may not have already been installed on the developer’s machine.  Also helps protect from global / local version inconsistencies.


m

**Comment by matthewberryman** [comment]
Yes but at some point you will need to run the CLI tools to build everything, no? In which case you'd either need to install globally (as node_modules/[cli-tool]/etc  is not on the PATH), or reference the specific path under node_modules/ from the scripts.

**Comment by mgvarley** [comment]
Yup true, I tend to reference anything like mocha in my scripts as ./node_modules/…  so the only thing that is truly global would be aurelia-cli but maybe I’m just paranoid! :o)

**Comment by matthewberryman** [comment]
No this is a sensible way of going just talking through the options and clarifying so I know what to do when I tweak jenkins :)
You could as far as I can tell also pick up aurelia-cli from node_modules - it gets installed there under node_modules/aurelia-cli/bin/aurelia-cli.js chmod 755 and with magic `#!/usr/bin/env node` so you could refer to that in the scripts. Do you want to have a go at packages.json as per your suggestion on https://github.com/urbanriskmap/petabencana.id/issues/21#issuecomment-262713734 and then anything else can be added back in to tidy this up?

**Comment by MaanasaPriyaa** [comment]
Sorry about the delay. As @ojha-url suggested, I deleted the outdated Readme file & moved the readme to project root petabencana.id.
