### ISSUE TITLE
Add upload photo functionality to cards/server

### ISSUE THREAD

**Issue by talltom** [urbanriskmap/petabencana.id#54]

**Comment by talltom** [comment]
Image upload currently giving CORS error, in discussion with @mgvarley 

```
XMLHttpRequest cannot load https://data-dev.petabencana.id/cards/tcard67/images. 
No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'https://dev.petabencana.id' is therefore not allowed access. The response had HTTP status code 415.
```

**Comment by talltom** [comment]
Interestingly, from Postman the following error is returned (for either .png or .jpg)

{
  "message": "Unsupported Media Type"
}

**Comment by mgvarley** [comment]
Hi Mayank - you need to set the correct media type otherwise API Gateway does not know how to encode it - this is passed as a Content-Type header parameter and must be a valid MIME type, one of: “image/png”, “image/gif” or “image/jpeg”.  Docs will be updated today but in the meantime see Postman screenshots attached.  (Note: looks like there is an issue on jpegs which I will need to investigate further but png is working fine).



























>

**Comment by mgvarley** [comment]
CORS is setup fine, for some reason these client side fetch libraries interpret all server side problems as CORS, not sure why!  If you see in the response the actual issue is HTTP 415 Unsupported Media type, you just need a Content-Type header parameter that reflects the appropriate MIME type so: “Image/png”, “image/gif” or “image/jpeg” and this should work fine.




>

**Comment by ojha-url** [comment]
@talltom, can you check if this works? 1fa60bc
You'll have to change the config vars currently placed in cards.js
     
      `if (imageObject) {
          let client = new HttpClient()
          .configure(x => {
            x.withBaseUrl(CONFIG_DATASRC1); //REPLACE with static part of aws s3 response url?
            x.withHeader('Content-Type', imageObject.type);
          });

          client.post(self.id + '/images', imageObject)
          .then(response => {
            console.log("Image upload SUCCESS: " + response);
          })
          .catch(response => {
            console.log("Image upload ERROR: " + response);
          });
        }`

**Comment by talltom** [comment]
This is still failing. Despite hard coding the content-type in bb379eed4b77125bd43f1b9fdd31b0a5305c46ae the following two errors are returned: 

```
POST https://data-dev.petabencana.id/cards/tcard67/images 415 (Unsupported Media Type)
r @ vendor-bundle.js:7
i @ vendor-bundle.js:2
r._settlePromiseFromHandler @ vendor-bundle.js:2
r._settlePromise @ vendor-bundle.js:2
r._settlePromiseCtx @ vendor-bundle.js:2
i._drainQueue @ vendor-bundle.js:1
i._drainQueues @ vendor-bundle.js:1
drainQueues @ vendor-bundle.js:1
/cards/tcard67/review:1 XMLHttpRequest cannot load https://data-dev.petabencana.id/cards/tcard67/images. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://dev.petabencana.id' is therefore not allowed access. The response had HTTP status code 415.
```

This is possibly related to #79 (dev server does not reflect local changes)

**Comment by talltom** [comment]
Also note @ojha-url - the card post request is still being submitted even when the user has not uploaded an image to the card.

**Comment by talltom** [comment]
@mgvarley Photo uploads with postman (png) return 200, but image_url field in grasp.reports is not set.

**Comment by mgvarley** [comment]
Yup, not implemented yet, will have this nailed on Monday along with other outstanding server stuff


>

**Comment by talltom** [comment]
OK, thanks.
