### ISSUE TITLE
Video link in the watch pane

### ISSUE THREAD

**Issue by asbarve** [urbanriskmap/petabencana.id#64]
"How to report" Video Iframe link form youtube/vimeo

**Comment by anexact** [comment]
We aren't going to post "How to report" until the WA modules are ready ... we have embargoed the contact number so that people don't send us reports which we are unable to receive. The "How to report" video is not worth posting if all the ways to report need to be removed, which, at present, they do. We'll have it ready to post into the page once cards, twitter, WA, are ready to go.

**Comment by asbarve** [comment]
Okey! closing this for Dec 8th milestone
