### ISSUE TITLE
Aurelia Indonesian Translation Fails on Dev deployment

### ISSUE THREAD

**Issue by talltom** [urbanriskmap/petabencana.id#79]
/@All (assigned) please note that even though I fixed #62 and got translation working locally, this does not currently work on dev server. My observations area:
- this is probably related to #77 
- changes to English language translation file **are** reflected on server
- Aurelia build does not output all user defined console.log messages in builds (as opposed to using au run locally)

**In summary our dev build is significantly different from what is seen locally.**

**Comment by matthewberryman** [comment]
Because fonts and css were placed under scripts/ (see https://github.com/urbanriskmap/petabencana.id/issues/80 ), someone had updated jenkins globbing from **/scripts/* (which is what it should have been as I cloned it from the prod project in jenkins), to **/scripts/*/* which grabs subdirectories but not files under scripts/*, i.e. it was not updating the js code. I've now made all globs for locales, scripts and assets the more generic **/{directory_name}/** which grabs files directly under the directories as well as the subdirectories. I've applied this to the -dev and -prod jenkins post-build s3 deployment steps, and also excluded node_modules (now that that's created under the root directory) - these doen't need to be deployed. When this work is merged to master you'd need to update the excludes list in the -prod project in jenkins to match -dev. I now see cards in Indonesian by default (although - shouldn't it pick my browser language set to en-au and translate to en?)

**Comment by matthewberryman** [comment]
Note I've just updated my comment to put the patterns in as code, as GitHub was interpreting the asterisks as markdown. So if you just read my previous comment prior to me making this one, please refresh the page to see it properly.
