### ISSUE TITLE
Catch large images in cards

### ISSUE THREAD

**Issue by talltom** [urbanriskmap/petabencana.id#87]
- server will return 413 "Request is too large"
- AWS max is 4.2mb

**Comment by matthewberryman** [comment]
I had a chat with @mgvarley about this—this particular limitation comes from the [payload size limit in lambda](http://docs.aws.amazon.com/lambda/latest/dg/limits.html)
There are some other possible workflows, for example you could use s3 (with transfer accelerator in the front of it), but then you have to push some of the logic to the client side, including the client getting its [signing and authentication](http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html) tokens, in order to prevent image overwrite (as s3 puts will otherwise permit overwrite, and versioning doesn't help us in this case).
And we could also consider what role my image processing lambda—or something else triggered from the s3 event on resized image storage—can play in signalling (via DB update) when image is processed.
There are some other limits although I looked into these and they don't really apply, namely:
* Max of 5GB for a put to s3—above that you must use a multipart upload, which is also recommended for >100MB files, but that's getting pretty extreme for images.
* We also need to consider lambda processing time. I'll take a quick look at that tomorrow.

This is getting a bit untidy; I will follow up via informal and formal AWS means to see if the limit on payload can be adjusted, or if there's some other architecture we haven't thought of that's neater.

**Comment by matthewberryman** [comment]
Something to explore is this framework (thanks to AWS for the tip) http://fineuploader.com/index.html
(This involves server side and client side code, so I'm listing it here and in the server issue)

**Comment by talltom** [comment]
Add notification client side to inform user image is too large.
- try this prior to submission on the photo card
